from os import chdir

execfile('check_fss.py')
chdir('plots')
print('fetching fss data')
fss_data = get_fss_data()
print('generating fss pitch plots')
plot_pitches(fss_data, savefigs=True)
print('fetching fss temperatures and binary data')
fss_temp_binary_data = get_fss_data(start='2011:001', pitch0=138, pitch1=140.5, interp=4.1)
print('generating fss temperature plots')
plot_temps(fss_temp_binary_data, savefigs=True)
print('generating fss bit analysis plots')
plot_binary(fss_temp_binary_data, savefigs=True)
close('all')
chdir('..')

execfile('check_spm_inputs.py')
chdir('plots')
print('fetching spm input data')
spm_data = get_spm_data()
print('generating fss plots')
plot_fss_errors(spm_data, savefigs=True)
print('generating css plots')
plot_css_errors(spm_data, savefigs=True)
close('all')
print('generating css error plots by year')
plot_css_errors_by_year(spm_data, savefigs=True)
close('all')
print('generating css error plots by bin')
plot_css_errors_bin(spm_data, savefigs=True, pitch_bin=50, roll_bin=0)
plot_css_errors_bin(spm_data, savefigs=True, pitch_bin=90, roll_bin=0)
plot_css_errors_bin(spm_data, savefigs=True, pitch_bin=135, roll_bin=0)
plot_css_errors_bin(spm_data, savefigs=True, pitch_bin=156, roll_bin=0)
plot_css_errors_bin(spm_data, savefigs=True, pitch_bin=50, roll_bin=5)
plot_css_errors_bin(spm_data, savefigs=True, pitch_bin=90, roll_bin=5)
plot_css_errors_bin(spm_data, savefigs=True, pitch_bin=135, roll_bin=5)
plot_css_errors_bin(spm_data, savefigs=True, pitch_bin=156, roll_bin=5)
plot_css_errors_bin(spm_data, savefigs=True, pitch_bin=90, roll_bin=10)
plot_css_errors_bin(spm_data, savefigs=True, pitch_bin=156, roll_bin=10)
close('all')
chdir('..')